# -*- coding: utf-8 -*-
"""tratamento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qkQ0rZ9Qk-tQqYtaAGRoXBfeakeFPv-9
"""

import pandas as pd

df = pd.read_csv('world_cup_comparisons.csv')

df.head()

df_filtrado = df[df['goals_z'] > 10]

grupo = df.groupby('goals_z').mean()

df['goals_z'].fillna(5, inplace=True)

del df['xg_z']

df.to_csv('dados_tratados.csv', index=False)